### PR TITLE
feat: add Rust chat example

### PR DESCRIPTION
**Pull request by rvolosatovs**
Add a chat server and client for the upcoming Summer of Code project.

The idea is really simple, the chat server listens on port 50000, assigns a randomly-generated ULID to each peer connecting and broadcasts messages to all connected peers.

Messages are simply lines of text (i.e. they should be newline-delimited)

Since there's no way to read from `stdin` in async manner, clients first have to write all messages, close STDIN (^D) and only then receive messages. @haraldh any ideas how to do this nicer? Can we write to stdout from `tokio::spawn` somehow?

In any case, we probably do want to have a web interface here, such that input would come from a socket (i.e. from the browser interface) cc @nickvidal 

# Example

```
nix build .#chat-server-rust-tokio && enarx run --wasmcfgfile ./result/Enarx.toml ./result/main.wasm
01GBX5FCPNAM8ZF16469C79ED4 peer joined
01GBX5FH2BM4G4XSVF3CTEJSEY peer joined
> 01GBX5FCPNAM8ZF16469C79ED4: peer 1
> 01GBX5FH2BM4G4XSVF3CTEJSEY: peer 2
> 01GBX5FCPNAM8ZF16469C79ED4: quick
> 01GBX5FH2BM4G4XSVF3CTEJSEY: brown
> 01GBX5FCPNAM8ZF16469C79ED4: fox
01GBX5FCPNAM8ZF16469C79ED4 peer left
```

```
nix build .#chat-client-rust-tokio && enarx run --wasmcfgfile ./result/Enarx.toml ./result/main.wasm
peer 1
quick
fox
01GBX5FCPNAM8ZF16469C79ED4 joined the chat
01GBX5FH2BM4G4XSVF3CTEJSEY joined the chat
01GBX5FCPNAM8ZF16469C79ED4: peer 1
01GBX5FH2BM4G4XSVF3CTEJSEY: peer 2
01GBX5FCPNAM8ZF16469C79ED4: quick
01GBX5FH2BM4G4XSVF3CTEJSEY: brown
01GBX5FCPNAM8ZF16469C79ED4: fox
^C
```

```
nix build .#chat-client-rust-tokio && enarx run --wasmcfgfile ./result/Enarx.toml ./result/main.wasm
peer 2
brown
01GBX5FH2BM4G4XSVF3CTEJSEY joined the chat
01GBX5FCPNAM8ZF16469C79ED4: peer 1
01GBX5FH2BM4G4XSVF3CTEJSEY: peer 2
01GBX5FCPNAM8ZF16469C79ED4: quick
01GBX5FH2BM4G4XSVF3CTEJSEY: brown
01GBX5FCPNAM8ZF16469C79ED4: fox
01GBX5FCPNAM8ZF16469C79ED4 left the chat
```

cc @rjzak

### CODE REVIEW

**Comment by haraldh** [comment]
Why does the client have to run in the a Keep? Shouldn't the native client just have to check, that the server cert is signed by profian (running in a keep)?

**Comment by rvolosatovs** [comment]
The intention is to have a private, secure chatroom. The server will have to validate the client's certificate to determine whether to admit the client or not.
In this scenario, a compromised client means a conpromised chat room.

If this were a real service, then the clients would be hosted services with a web UI.

The overall idea is that clients are associated with an OIDC identity, e.g. a Github username. The client auth state could also then securely be stored by the keep.

**Comment by rvolosatovs** [comment]
To clarify, this is really not about the chat, the end goal is to have a peer-to-peer networked application, where workloads running in Enarx can establish trust relationships given what Enarx platform offers.

Making this a chat is just a simplification for SoC. This is essentially just an exploration into what we can achieve with a network of communicating Enarx keeps.

**Review by rjzak — APPROVED** [review]
Looks good to me

**Pull request merged**
